### ISSUE TITLE
Tracking issue for which posts you want to see

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#106]
There have been multiple issues opened related to this same thing. I'm conglomerating them

- [x] Root posts by you [always on]
- [x] Root posts by people you follow [always on]
- [x] Replies by you [always on]
- [ ] Direct ancestors of replies by you {my_reply_ancestors}
- [ ] Replies by people you follow {follower_replies}
- [ ] Direct ancestors of replies by people you follow {follower_reply_ancestors}
- [ ] Replies by others to your posts {others_reply_to_mine}
- [ ] Replies by others to people you follow {others_reply_to_followed}
- [ ] Any post mentioning you {mentioning_me}
- [ ] Any post mentioning people you follow {mentioning_followed}
- [ ] Posts reacted to by people you follow (reacted_to_by_followed}
- [ ] All posts on the relays you are connected to {all_posts}

**Comment by mikedilger** [comment]
The settings that I think we should have keeps changing. This list isn't really useful. So I'm dropping this issue in this format.
