### ISSUE TITLE
Person lists, tracking

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#576]
This work should progress on the "lists" branch.

NOTE:  The lists branch is on a separate migration, so you cannot easily switch back and forth with unstable.

Person List UI work:
- [ ] Prompt for login and Wait for migration pages look ugly.  We need to style these.
- [ ] Person page: spruce up how you add/remove them from lists (follow dtonon's design)
- [x] List of Lists page: Delete list happens immediately right now.  We need a confirmation popup.
- [x] List page:  We need a way to add a person...  this should replace "follow new" in the menu, and "follow new" should then be removed from the menu (as well as it's page).
- [ ] Feeds Menu:  This can get too long. We need to work out how to handle that
- [x] Create a new list doesn't do anything yet.  We need a popup that prompts for the list name, then we need to pass that in and actually create the new list.

Person List work assigned to Mike:
- [x] Dates at the tops of the person list do not match. I haven't checked why.
- [x] storage::get_deletion to go away, replaced by get_deletions. There can be more than one.
- [x] Add a login-at-startup setting (true by default)
- [x] Be sure we preserve other tags in lists when we write the events. Other clients add "a" and "t" tags and maybe others too.

**Comment by mikedilger** [comment]
I'm closing this and the remaining UI work will be opened under a new issue.
