### ISSUE TITLE
Event processing checklist

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#72]
ORIG issue:  relay.last_find_people is not being set. It used to be, at least on wss://relay.damus.io.
NOW:

We need to update all of the following as events come in:
- [x] all events
    - [x] save into event table
    - [x] save event_seen on relay data
    - [x] save all tags into event_tags table
- [x] 'e' tag relays field:
    - [x] add to relays list
- [x] 'p' tag relays
    - [x] add to relays list
    - [x] add to person_relay pair and update last_suggested_bytag
- [ ]  kind 3 events (other people's contact lists)
     - [x] (nonstandard but common from content), update person_relay pair and update last_suggested_kind3
 - [x] kind 0 metadata events
    - [x] look up NIP-05/NIP-35 data, update person_relay and set last_suggested_nip35
- [x] when tags indicate a reply
    - [x] update event_relationship, set reply relationship
    - [x] update last_reply date in globals up the stack
    - [x] save desired parent event id (in memory only)
- [ ] when tags indicate a quote
    - [ ] update event_relationship, set quote relationship
    - [ ] save desired parent event id (in memory only)
- [x] when tags indicate a reaction
    - [x] update event_relationship, set reaction relationship
    - [x] save desired parent event id (in memory only)
- [x] when tags indicate a deletion
    - [x] update event_relationship, set deletion relationship

**Comment by mikedilger** [comment]
The rest of this is bumped to 0.5

**Comment by mikedilger** [comment]
kind-2 is dead.
saving other people's kind-3 events is being worked on under a different issue
quote relationships (including reposts) aren't really needed IMHO, but we could open that in another issue if it is.
