### ISSUE TITLE
Finish multiple refactors

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#831]
This is a tracking issue for many refactors that have been started but never completed.

- [ ] We massively refactored identity/signer so that we could do NIP-46 as a client, but never did NIP-46 as a client.
- [ ] I recently brought the filters out of the minions and into FilterSet to avoid code duplication and so that they could be used by the feed #783, but they aren't yet used by the feed
- [ ] I created storage/table.rs as generic reusable code for an LMDB table. I proofed it with person3_table, but it has not been used anywhere else.  All the other LMDB tables could(should?) migrate over to this for consistency and clarity and to avoid so much code duplication.
- [ ] I moved relay selection code to relay.rs, but the goal was #825 which I was not able to reach due to performance problems that I never figured out (after nearly a week of frustrating attempts to do so) (local m2 branch)
- [ ] A lot of refactoring was done in order to fix #772, by changing the Feed::Thread to an EventReference (from an Id), but that never quite got there and got bogged down (local remuck branch)
- [ ] In order to view multiple URLs as the same relay I defined RelayOrigin, but never found useful code changes that utilized it (local relay-origin branches)

**Comment by bu5hm4nn** [comment]
Any update on these?

**Comment by mikedilger** [comment]
* The first one, identity/signer, we got stuck on an async bug so we still never got to be a nip46 client.
* The second one it looks like didn't quite happen, but it's not obvious
* The third one, we have more tables now: followings_table, handlers_table.  But most databases aren't using it.
* 4th: not sure.  I still have a local m2 branch from August.
* 5th: not sure.  I still have a local remuck branch.
* 6th: not sure, I have 3 local relay-origin branches.
