### ISSUE TITLE
TRACKING ISSUE: Finish feed

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#84]
- [ ] #79 especially including ranking person_relay pairs
- [ ] #70 and #72, at least kind2 and kind3
- [ ] Compare feed to what we see on damus app
- [ ] Compare feed to what we see on astral.ninja

**Comment by mikedilger** [comment]
Now that we are using milestones, we don't need these tracking issues.
