### ISSUE TITLE
TRACKING ISSUE: ALPHA Release

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#94]
This is what I want to finish before an alpha release (which will be called 0.4)
I will try not to add anything to this list, but if something obviously important comes up I might.

- [ ] #121
- [ ] #106, at least replies to your own posts
- [x] #98
- [x] #95
- [x] #90
- [x] #92 
- [x] #77
- [x] #82
- [x] #81 
- [ ] #79 
- [ ] #70
- [x] #69 
- [x] #83 
- [x] #78 
- [ ] #74 
- [ ] #73
- [ ] #72 except kind=10001
- [ ] #70 except kind=10001
- [x] #68
- [x] #67 we need eye candy, setting to disable
- [x] #53 1 more to go
- [ ] #46 
- [ ] #45
- [ ] #43  setting to disable
- [x] #42 
- [ ] #38 
- [ ] #4

I want these too if possible, but if too hard we can go alpha withtout

- [x] #76 (if possible) or else choose just one font with many symbols
- [x] #75 (if possible)

**Comment by mikedilger** [comment]
Now that we are using milestones, we don't need tracking issues.
