### ISSUE TITLE
Checklist from 0xtr

### ISSUE THREAD

**Issue by mikedilger** [mikedilger/gossip#99]
Some features just on the top of my mind in no particular order:
- [x] Edit relays
    - [x] What we have is rudimentary still. You can choose relays to post to.
- [x] DMs
    - [x] Not even started on this one.
- [x] NIP-05 support on profiles
    - [x] We have nip-05 information, we display it, but we don't yet verify it
    - [x] We don't yet have setting/syncing of your own metadata
- [x] Click on a reply and display the whole thread
    - [x] We have threading. The whole thing is threaded when it's on. We may need to tuck replies under a collapsible element though.
- [x] Search for users based on either pubkey or NIP-05 identifier

Less important but nice to have in the future:
- [x] Edit LNURL in metadata

- [x] Lightning payment button on the profile page if the user has set the LNURL field

- [x] Render BOLT-11 invoices
- [x] See which relays other users are connected to (Astral supports this today)
    - [x] Track (not showing) which relays other users use
    - [x] Track (not showing) which relays events came in on
- [ ] See followers/follows for a user (Astral supports this today)
- [x] Boosts show up just like a retweet on Twitter

- [x] When I write the '@' symbol, give me help to find the user I want to tag. Astral does this pretty well today.
- [x] Freetext search for users
- [x] Connection status for relays. Makes it easier to spot dead relays.
